version: '3'

services:

  mysql:
    container_name: secture-mysql
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/docker/mysql/migrations:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: secture
      MYSQL_USER: secture
      MYSQL_PASSWORD: secture
      MYSQL_ROOT_PASSWORD: secture
    command: ["--default-authentication-plugin=mysql_native_password"]


  nginx:
    container_name: secture-nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - .:/var/www/Secture
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    container_name: secture-php
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/Secture
    env_file:
      - .env
    depends_on:
      - mysql
